# initially look at 3d plots of inj_mbar and bias_v effect on fcv1_i
python3 scatter_plot.py --x_col extraction_i --y_col bias_v --z_col fcv1_i --a_col fcv1_i --elevations 10 --filenames ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_00_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_01_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_03_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_04_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_05_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_06_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_08a_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_08b_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_08c_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_08d_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_09_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_10a_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_10_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_11b_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_11_processed
python3 scatter_plot.py --x_col extraction_i --y_col bias_v --z_col fcv1_i --a_col fcv1_i --elevations 10 --filenames ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_00_processed
python3 scatter_plot.py --x_col extraction_i --y_col bias_v --z_col fcv1_i --a_col fcv1_i --elevations 10 --filenames ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_01_processed
python3 scatter_plot.py --x_col extraction_i --y_col bias_v --z_col fcv1_i --a_col fcv1_i --elevations 10 --filenames ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_03_processed
python3 scatter_plot.py --x_col extraction_i --y_col bias_v --z_col fcv1_i --a_col fcv1_i --elevations 10 --filenames ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_04_processed
python3 scatter_plot.py --x_col extraction_i --y_col bias_v --z_col fcv1_i --a_col fcv1_i --elevations 10 --filenames ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_05_processed
python3 scatter_plot.py --x_col extraction_i --y_col bias_v --z_col fcv1_i --a_col fcv1_i --elevations 10 --filenames ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_06_processed
python3 scatter_plot.py --x_col extraction_i --y_col bias_v --z_col fcv1_i --a_col fcv1_i --elevations 10 --filenames ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_08a_processed
python3 scatter_plot.py --x_col extraction_i --y_col bias_v --z_col fcv1_i --a_col fcv1_i --elevations 10 --filenames ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_08b_processed
python3 scatter_plot.py --x_col extraction_i --y_col bias_v --z_col fcv1_i --a_col fcv1_i --elevations 10 --filenames ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_08c_processed
python3 scatter_plot.py --x_col extraction_i --y_col bias_v --z_col fcv1_i --a_col fcv1_i --elevations 10 --filenames ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_08d_processed
python3 scatter_plot.py --x_col extraction_i --y_col bias_v --z_col fcv1_i --a_col fcv1_i --elevations 10 --filenames ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_09_processed
python3 scatter_plot.py --x_col extraction_i --y_col bias_v --z_col fcv1_i --a_col fcv1_i --elevations 10 --filenames ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_10a_processed
python3 scatter_plot.py --x_col extraction_i --y_col bias_v --z_col fcv1_i --a_col fcv1_i --elevations 10 --filenames ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_10_processed
python3 scatter_plot.py --x_col extraction_i --y_col bias_v --z_col fcv1_i --a_col fcv1_i --elevations 10 --filenames ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_11b_processed
python3 scatter_plot.py --x_col extraction_i --y_col bias_v --z_col fcv1_i --a_col fcv1_i --elevations 10 --filenames ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_11_processed

# fcv1_i_normalized analysis
python3 scatter_plot.py --x_col extraction_i --y_col bias_v --z_col inj_mbar --a_col fcv1_i_normalized --elevations 10 --filenames ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_00_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_01_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_03_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_04_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_05_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_06_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_08a_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_08b_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_08c_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_08d_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_09_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_10a_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_10_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_11b_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_11_processed
python3 scatter_plot.py --x_col bias_i --y_col bias_v --z_col inj_mbar --a_col fcv1_i_normalized --elevations 10 --filenames ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_00_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_01_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_03_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_04_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_05_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_06_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_08a_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_08b_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_08c_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_08d_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_09_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_10a_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_10_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_11b_processed ../../../processed_data/vary_pressure_and_bias_voltage/watch_data_11_processed
