#!/bin/sh

python3 test.py --train_csv_files watch_data_01_clean watch_data_02_clean watch_data_03_clean watch_data_04_clean watch_data_05_clean watch_data_06_clean watch_data_07_clean watch_data_08a_clean watch_data_08b_clean watch_data_08c_clean watch_data_08d_clean watch_data_09_clean watch_data_10_clean watch_data_10a_clean watch_data_11_clean watch_data_11b_clean --test_csv_file watch_data_00_clean

python3 test.py --train_csv_files watch_data_00_clean watch_data_02_clean watch_data_03_clean watch_data_04_clean watch_data_05_clean watch_data_06_clean watch_data_07_clean watch_data_08a_clean watch_data_08b_clean watch_data_08c_clean watch_data_08d_clean watch_data_09_clean watch_data_10_clean watch_data_10a_clean watch_data_11_clean watch_data_11b_clean --test_csv_file watch_data_01_clean

python3 test.py --train_csv_files watch_data_00_clean watch_data_01_clean watch_data_03_clean watch_data_04_clean watch_data_05_clean watch_data_06_clean watch_data_07_clean watch_data_08a_clean watch_data_08b_clean watch_data_08c_clean watch_data_08d_clean watch_data_09_clean watch_data_10_clean watch_data_10a_clean watch_data_11_clean watch_data_11b_clean --test_csv_file watch_data_02_clean

python3 test.py --train_csv_files watch_data_00_clean watch_data_01_clean watch_data_02_clean watch_data_04_clean watch_data_05_clean watch_data_06_clean watch_data_07_clean watch_data_08a_clean watch_data_08b_clean watch_data_08c_clean watch_data_08d_clean watch_data_09_clean watch_data_10_clean watch_data_10a_clean watch_data_11_clean watch_data_11b_clean --test_csv_file watch_data_03_clean

python3 test.py --train_csv_files watch_data_00_clean watch_data_01_clean watch_data_02_clean watch_data_03_clean watch_data_05_clean watch_data_06_clean watch_data_07_clean watch_data_08a_clean watch_data_08b_clean watch_data_08c_clean watch_data_08d_clean watch_data_09_clean watch_data_10_clean watch_data_10a_clean watch_data_11_clean watch_data_11b_clean --test_csv_file watch_data_04_clean

python3 test.py --train_csv_files watch_data_00_clean watch_data_01_clean watch_data_02_clean watch_data_03_clean watch_data_04_clean watch_data_06_clean watch_data_07_clean watch_data_08a_clean watch_data_08b_clean watch_data_08c_clean watch_data_08d_clean watch_data_09_clean watch_data_10_clean watch_data_10a_clean watch_data_11_clean watch_data_11b_clean --test_csv_file watch_data_05_clean

python3 test.py --train_csv_files watch_data_00_clean watch_data_01_clean watch_data_02_clean watch_data_03_clean watch_data_04_clean watch_data_05_clean watch_data_07_clean watch_data_08a_clean watch_data_08b_clean watch_data_08c_clean watch_data_08d_clean watch_data_09_clean watch_data_10_clean watch_data_10a_clean watch_data_11_clean watch_data_11b_clean --test_csv_file watch_data_06_clean

python3 test.py --train_csv_files watch_data_00_clean watch_data_01_clean watch_data_02_clean watch_data_03_clean watch_data_04_clean watch_data_05_clean watch_data_06_clean watch_data_08a_clean watch_data_08b_clean watch_data_08c_clean watch_data_08d_clean watch_data_09_clean watch_data_10_clean watch_data_10a_clean watch_data_11_clean watch_data_11b_clean --test_csv_file watch_data_07_clean

python3 test.py --train_csv_files watch_data_00_clean watch_data_01_clean watch_data_02_clean watch_data_03_clean watch_data_04_clean watch_data_05_clean watch_data_06_clean watch_data_07_clean watch_data_08b_clean watch_data_08c_clean watch_data_08d_clean watch_data_09_clean watch_data_10_clean watch_data_10a_clean watch_data_11_clean watch_data_11b_clean --test_csv_file watch_data_08a_clean

python3 test.py --train_csv_files watch_data_00_clean watch_data_01_clean watch_data_02_clean watch_data_03_clean watch_data_04_clean watch_data_05_clean watch_data_06_clean watch_data_07_clean watch_data_08a_clean watch_data_08c_clean watch_data_08d_clean watch_data_09_clean watch_data_10_clean watch_data_10a_clean watch_data_11_clean watch_data_11b_clean --test_csv_file watch_data_08b_clean

python3 test.py --train_csv_files watch_data_00_clean watch_data_01_clean watch_data_02_clean watch_data_03_clean watch_data_04_clean watch_data_05_clean watch_data_06_clean watch_data_07_clean watch_data_08a_clean watch_data_08b_clean watch_data_08d_clean watch_data_09_clean watch_data_10_clean watch_data_10a_clean watch_data_11_clean watch_data_11b_clean --test_csv_file watch_data_08c_clean

python3 test.py --train_csv_files watch_data_00_clean watch_data_01_clean watch_data_02_clean watch_data_03_clean watch_data_04_clean watch_data_05_clean watch_data_06_clean watch_data_07_clean watch_data_08a_clean watch_data_08b_clean watch_data_08c_clean watch_data_09_clean watch_data_10_clean watch_data_10a_clean watch_data_11_clean watch_data_11b_clean --test_csv_file watch_data_08d_clean

python3 test.py --train_csv_files watch_data_00_clean watch_data_01_clean watch_data_02_clean watch_data_03_clean watch_data_04_clean watch_data_05_clean watch_data_06_clean watch_data_07_clean watch_data_08a_clean watch_data_08b_clean watch_data_08c_clean watch_data_08d_clean watch_data_10_clean watch_data_10a_clean watch_data_11_clean watch_data_11b_clean --test_csv_file watch_data_09_clean

python3 test.py --train_csv_files watch_data_00_clean watch_data_01_clean watch_data_02_clean watch_data_03_clean watch_data_04_clean watch_data_05_clean watch_data_06_clean watch_data_07_clean watch_data_08a_clean watch_data_08b_clean watch_data_08c_clean watch_data_08d_clean watch_data_09_clean watch_data_10a_clean watch_data_11_clean watch_data_11b_clean --test_csv_file watch_data_10_clean

python3 test.py --train_csv_files watch_data_00_clean watch_data_01_clean watch_data_02_clean watch_data_03_clean watch_data_04_clean watch_data_05_clean watch_data_06_clean watch_data_07_clean watch_data_08a_clean watch_data_08b_clean watch_data_08c_clean watch_data_08d_clean watch_data_09_clean watch_data_10_clean watch_data_11_clean watch_data_11b_clean --test_csv_file watch_data_10a_clean

python3 test.py --train_csv_files watch_data_00_clean watch_data_01_clean watch_data_02_clean watch_data_03_clean watch_data_04_clean watch_data_05_clean watch_data_06_clean watch_data_07_clean watch_data_08a_clean watch_data_08b_clean watch_data_08c_clean watch_data_08d_clean watch_data_09_clean watch_data_10_clean watch_data_10a_clean watch_data_11b_clean --test_csv_file watch_data_11_clean

python3 test.py --train_csv_files watch_data_00_clean watch_data_01_clean watch_data_02_clean watch_data_03_clean watch_data_04_clean watch_data_05_clean watch_data_06_clean watch_data_07_clean watch_data_08a_clean watch_data_08b_clean watch_data_08c_clean watch_data_08d_clean watch_data_09_clean watch_data_10_clean watch_data_10a_clean watch_data_11_clean --test_csv_file watch_data_11b_clean

